name: Generate dotenv
description: Utilize github vars and secrets to create dotenv file from them following instructions
author: kindkitchen
inputs:
  vars_obj:
    description: "In most cases may be toJson(vars). Or any other key-value json string"
    default: "{}"
  secrets_obj:
    description: "In most cases may be toJson(secrets). Or any other key-value json stringO"
    default: "{}"
  dotenv_path:
    description: The path, where generated dotenv file will be placed (the default is ./.env)
    default: ./.env
  dotenv_content:
    description: The literal content of the dotenv file. Will be placed at the bottom of generated file.
    default: ""
  vars_include_pattern:
    description: 'Regex by which the keys from vars will be included. (default: "*")'
    default: "*"
  vars_exclude_pattern:
    description: "Regex by which the keys from vars will not be included. Will override `include_vars_pattern` on conflict. (default: null)"
    required: false
  secrets_include_pattern:
    description: 'Regex by which the keys from secrets will be included. (default: "*")'
    default: "*"
  secrets_exclude_pattern:
    description: "Regex by which the keys from secrets will not be included. Will override `include_secrets_pattern` on conflict. (default: null)"
    required: false
  content_from_vars_include_pattern:
    description: "Regex by which the keys from vars will be treated as part of content (many lines with variables) and these contents will be attached. (default: null)"
    default: ""
  content_from_secrets_include_pattern:
    description: "Regex by which the keys from secrets will be treated as part of content (many lines with variables) and these contents will be attached. (default: null)"
    default: ""

runs:
  using: composite
  steps:
    - id: merge_vars_with_content
      name: "1. Merge contents of batch-vars"
      shell: bash
      env:
        JSON_KEY_CONTENT: ${{ inputs.vars_obj }}
        DOTENV_PATH: ${{ inputs.dotenv_path }}
        INCLUDE: ${{ inputs.content_from_vars_include_pattern }}
      run: |
        echo "$JSON_KEY_CONTENT" | jq -r --arg include "$INCLUDE" \
          'to_entries | map(select(.key | test($include))) | .[].value' \
          >> $DOTENV_PATH

    - id: merge_vars_with_kv
      name: "2. Merge key=value from vars"
      shell: bash
      env:
        DOTENV_PATH: ${{ inputs.dotenv_path }}
        JSON_KEY_VALUE: ${{ inputs.vars_obj }}
        INCLUDE: ${{ inputs.vars_include_pattern }}
        EXCLUDE: ${{ inputs.vars_exclude_pattern }}
      run: |
        echo "$JSON_KEY_CONTENT" | jq -r --arg include "$INCLUDE" --arg exclude "$EXCLUDE" \
          'to_entries | map(select(.key | test($include)) | select(.key | test($exclude) | not)) | | .[] | "\(.key)=\(.value | @json)"' \
          >> $DOTENV_PATH
