name: e2e v1.0.0

on:
  push:
    tags:
      - v1.0.0
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Self invocation
        uses: kindkitchen/genv@v1.0.0
        with:
          vars_obj: '{ "HELLO": "world" }'
          secrets_obj: '{ "CONFIG": "NAME=king", "SUDO_KEY": "alahamora", "DOOM": "boom!" }'
          content_from_secrets_include_pattern: "^CONFIG$"
          secrets_include_pattern: "DO"
          secrets_exclude_pattern: "DOOM"
          dotenv_content: |
            LITERAL=literal
            LITERAL_2=literal_2

      - name: Assert file was written
        run: >
          [ -f ./.env ] || { echo "File not found"; exit 1; }
      - name: Debug content
        run: |
          echo "actual file's content:"
          cat ./.env
          echo "expected:"
          echo -e "HELLO=\"world\"\nNAME=king\nSUDO_KEY=\"alahamora\"\nLITERAL=literal\nLITERAL_2=literal_2"
      - name: Assert file's content
        run: >
          [ "$(cat ./.env)" = "$(echo -e "HELLO=\"world\"\nNAME=king\nSUDO_KEY=\"alahamora\"\nLITERAL=literal\nLITERAL_2=literal_2")" ] || exit 1
